// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "api-bed-covid/model"

	mock "github.com/stretchr/testify/mock"
)

// Scraper is an autogenerated mock type for the Scraper type
type Scraper struct {
	mock.Mock
}

// GetHospitalDetail provides a mock function with given fields: hospitalCode
func (_m *Scraper) GetHospitalDetail(hospitalCode string) (model.HospitalDetail, error) {
	ret := _m.Called(hospitalCode)

	var r0 model.HospitalDetail
	if rf, ok := ret.Get(0).(func(string) model.HospitalDetail); ok {
		r0 = rf(hospitalCode)
	} else {
		r0 = ret.Get(0).(model.HospitalDetail)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hospitalCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProvinceAvailability provides a mock function with given fields: provinceID
func (_m *Scraper) GetProvinceAvailability(provinceID int) ([]model.HospitalSummary, error) {
	ret := _m.Called(provinceID)

	var r0 []model.HospitalSummary
	if rf, ok := ret.Get(0).(func(int) []model.HospitalSummary); ok {
		r0 = rf(provinceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.HospitalSummary)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(provinceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
